import "./globals.scss";
import Navbar from "./Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" w-full flex flex-col items-center justify-center">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
